name: Agents.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # See: https://github.com/denoland/setup-deno
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Check Code Formatting
        run: deno fmt --check
        continue-on-error: true

      - name: Lint Sources
        run: deno lint
        continue-on-error: true

      - name: Run Tests
        run: deno task test

  publish:
    needs: test
    if: ${{ github.ref == 'main' }}

    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write # Used for authentication with JSR.

    steps:
      - uses: actions/checkout@v4

      - name: Publish to JSR
        run: npx jsr publish
